# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
before_install:
  - sh ./conf/travis-install-mpi.sh
  # Work around OpenMPI attempting to create overly long temporary
  # file names - and erroring as a result
  - export TMPDIR=/tmp
  # Work around MacOS/OpenMPI issue:
  #   https://github.com/open-mpi/ompi/issues/6518
  #   https://github.com/open-mpi/ompi/issues/5798
  - export OMPI_MCA_btl=self,tcp
jobs:
  include:
    - stage: MPI
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add("MPI");
          using MPI;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.test();'
      after_success: skip
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.add("Healpix");
          Pkg.add("Plots");
          include("docs/make.jl");'
      after_success: skip
